openapi: 3.0.1
info:
  title: CoChannelProfile_1.0.0-tsi.240103.1055+simulator.1
  version: 1.0.0

paths:

########################################################################################################################
#   Generic Paths
########################################################################################################################
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/co-channel-profile-1-0:co-channel-profile-pac/co-channel-profile-capability:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedCoChannelProfileCapability
      summary: 'Provides CoChannelProfileCapability from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'CoChannelProfileCapability provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - co-channel-profile-1-0:co-channel-profile-capability
                properties:
                  co-channel-profile-1-0:co-channel-profile-capability:
                    $ref: '#/components/schemas/co-channel-profile-capability'
                example:
                  co-channel-profile-1-0:co-channel-profile-capability:
                    xpic-is-avail: true
                    mimo-is-avail: true
                    number-of-mimo-channels-max: 2
                    alic-is-avail: true
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=cache/control-construct={mountName}/profile-collection/profile={uuid}/co-channel-profile-1-0:co-channel-profile-pac/co-channel-profile-configuration:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
      - $ref: '#/components/parameters/uuid'
      - $ref: '#/components/parameters/fields'
    get:
      operationId: getCachedCoChannelProfileConfiguration
      summary: 'Provides CoChannelProfileConfiguration from cache'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'CoChannelProfileConfiguration provided from cache'
          content:
            application/json:
              schema:
                type: object
                required:
                  - co-channel-profile-1-0:co-channel-profile-configuration
                properties:
                  co-channel-profile-1-0:co-channel-profile-configuration:
                    $ref: '#/components/schemas/co-channel-profile-configuration'
                example:
                  co-channel-profile-1-0:co-channel-profile-configuration:
                    external-label: 'string'
                    kind-of-co-channel-profile: 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_XPIC'
                    logical-termination-point-list:
                      - 'string'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'

  /core-model-1-4:network-control-domain=live/control-construct={mountName}/co-channel-profile-1-0:create-co-channel-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postCreateCoChannelProfile
      summary: 'Creates new instance of CoChannelProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - kind-of-co-channel-profile
                  properties:
                    external-label:
                      type: string
                    kind-of-co-channel-profile:
                      type: string
                      enum:
                        - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_XPIC'
                        - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_MIMO'
                        - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_ALIC'
                        - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_NOT_YET_DEFINED'
                    logical-termination-point-list:
                      type: array
                      minItems: 0
                      items:
                        type: string
      responses:
        '200':
          description: 'New instance of CoChannelProfile created'
          content:
            application/json:
              schema:
                type: object
                required:
                  - co-channel-profile-1-0:output
                properties:
                  co-channel-profile-1-0:output:
                    type: object
                    required:
                      - created-co-channel-profile
                    properties:
                      created-co-channel-profile:
                        type: string
              example:
                co-channel-profile-1-0:output:
                  created-co-channel-profile: 'string'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=live/control-construct={mountName}/co-channel-profile-1-0:modify-co-channel-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postModifyCoChannelProfile
      summary: 'Modifies an existing CoChannelProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                    - co-channel-profile-to-be-modified
                  properties:
                    co-channel-profile-to-be-modified:
                      type: string
                    external-label:
                      type: string
                    new-logical-termination-point-list:
                      type: array
                      minItems: 0
                      items:
                        type: string
      responses:
        '204':
          description: 'Instance of CoChannelProfile updated'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'
  /core-model-1-4:network-control-domain=live/control-construct={mountName}/co-channel-profile-1-0:delete-co-channel-profile:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
      - $ref: '#/components/parameters/x-correlator'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
      - $ref: '#/components/parameters/mountName'
    post:
      operationId: postDeleteCoChannelProfile
      summary: 'Deletes an instance of CoChannelProfile'
      tags:
        - IndividualServices
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - input
              properties:
                input:
                  type: object
                  required:
                  - obsolete-co-channel-profile
                  properties:
                    obsolete-co-channel-profile:
                      type: string
      responses:
        '204':
          description: 'Instance of CoChannelProfile deleted'
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            exec-time:
              $ref: '#/components/headers/exec-time'
            backend-time:
              $ref: '#/components/headers/backend-time'
            life-cycle-state:
              $ref: '#/components/headers/life-cycle-state'
        '4XX':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        '500':
          $ref: '#/components/responses/responseForErroredServiceRequests'
        default:
          $ref: '#/components/responses/responseForErroredServiceRequests'


########################################################################################################################
#   Common Components
########################################################################################################################
components:
  parameters:
    user:
      name: user
      in: header
      required: true
      schema:
        type: string
        example: 'User Name'
      description: 'User identifier from the system starting the service call'
    originator:
      name: originator
      in: header
      required: true
      schema:
        type: string
        minLength: 3
        example: 'Resolver'
      description: >
        'Identification for the system consuming the API, as defined in
         [/core-model-1-4:control-construct/logical-termination-point={uuid}/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
    x-correlator:
      name: x-correlator
      in: header
      required: true
      schema:
        type: string
        pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
        description: 'Empty string accepted from external applications.'
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses'
    trace-indicator:
      name: trace-indicator
      in: header
      required: true
      schema:
        type: string
        pattern: '^([0-9]+)(\.([0-9]+))*$'
        description: 'Empty string accepted from external applications.'
        example: '1.3.1'
      description: 'Sequence of request numbers along the flow'
    customer-journey:
      name: customer-journey
      in: header
      required: true
      schema:
        type: string
        example: 'Unknown value'
      description: 'Holds information supporting customer’s journey to which the execution applies'
    mountName:
      name: mountName
      in: path
      required: true
      schema:
        type: string
        example: '222250001'
      description: 'The mountName of the device that is addressed by the request'
    uuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within the device'
    uuid1:
      name: uuid1
      in: path
      required: true
      schema:
        type: string
        example: 'LTP-MWPS-TTP-1-1'
      description: 'Another instance identifier that is unique within the device'
    localId:
      name: localId
      in: path
      required: true
      schema:
        type: string
        example: 'LP-MWPS-TTP-1-1'
      description: 'Instance identifier that is unique within its list'
    fields:
      name: fields
      in: query
      required: false
      schema:
        type: string
        example: 'node(node-id;netconf-node-topology:connection-status)'
      description: 'Query parameter to filter ressources according to RFC8040 fields filter spec'
  responses:
    responseForErroredServiceRequests:
      description: 'Response in case of errored service requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
      headers:
        x-correlator:
          schema:
            type: string
            pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
            example: '550e8400-e29b-11d4-a716-446655440000'
          description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
        exec-time:
          schema:
            type: integer
            example: 1100
          description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
        backend-time:
          schema:
            type: integer
            example: 850
          description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    responseForErroredOamRequests:
      description: 'Response in case of errored OaM requests'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorDescription'
  headers:
    x-correlator:
      schema:
        type: string
        example: '550e8400-e29b-11d4-a716-446655440000'
      description: 'UUID for the service execution flow that allows to correlate requests and responses. Its value must be identical at the response compared with its corresponding request'
    exec-time:
      schema:
        type: integer
        example: 1100
      description: 'Value written by the service provider, reporting the total elapsed time for the execution, including all the additional processing needed to retrieve the data from the backend service. Expressed in milliseconds'
    backend-time:
      schema:
        type: integer
        example: 850
      description: 'Value written by the service provider, reporting the elapsed time for data retrieval from the backend (service invocation, database access…). Expressed in milliseconds'
    life-cycle-state:
      schema:
        type: string
        enum:
          - 'EXPERIMENTAL'
          - 'OPERATIONAL'
          - 'DEPRECATED'
          - 'OBSOLETE'
          - 'UNKNOWN'
          - 'NOT_YET_DEFINED'
        example: 'EXPERIMENTAL'
  schemas:
    errorDescription:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    co-channel-profile-capability:
      type: object
      required:
        - xpic-is-avail
        - mimo-is-avail
        - number-of-mimo-channels-max
        - alic-is-avail
      properties:
        xpic-is-avail:
          type: boolean
        mimo-is-avail:
          type: boolean
        number-of-mimo-channels-max:
          type: integer
          format: int8
        alic-is-avail:
          type: boolean
    co-channel-profile-configuration:
      type: object
      required:
        - external-label
        - kind-of-co-channel-profile
      properties:
        external-label:
          type: string
        kind-of-co-channel-profile:
          type: string
          enum:
            - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_XPIC'
            - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_MIMO'
            - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_ALIC'
            - 'co-channel-profile-1-0:KIND_OF_CO_CHANNEL_PROFILE_TYPE_NOT_YET_DEFINED'
        logical-termination-point-list:
          type: array
          minItems: 0
          items:
            type: string

  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: operation-key
    basicAuth:
      type: http
      scheme: basic
